import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import { Grid, GridItem} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body>
                <Providers>
                    <Grid templateAreas={`
                    "header header header header"
                    "nav . main ."
                    "footer footer footer footer"`}
                          gridTemplateRows={"60px 1fr 30px"} gridTemplateColumns={"150px 1fr minmax(200px, 1200px) 1fr"} h={"100vh"} gap={"1"}>
                        <GridItem bg="red" area={"header"}>
                            Header
                        </GridItem>
                        <GridItem bg="blue" area={"nav"}>
                            Nav
                        </GridItem>
                        <GridItem area={"main"} display={"flex"} alignItems="center" justifyContent="center">
                            {children}
                        </GridItem>
                        <GridItem bg="teal.500" area={"footer"}>
                            Footer
                        </GridItem>
                    </Grid>
                </Providers>
            </body>
        </html>
    );
}
